var comics = 
	[
		{
			_id: 0,
			title: "Daredevil",
			description: "Daredevil tells the story of Matt Murdock, blind lawyer by day, relentless avenger of justice by night. A gritty tale of crime and corruption, Daredevil's noir aesthetic and history of top-shelf talent has made it one of Marvel's most consistently award-winning titles.",
			image: "daredevil.jpg",
			year: "2011/1/1",
			recommended: "Si",
			edition: 1,
			creator: "Ed Brubake",
			qualification: 5,
		},
		{
			_id: 1,
			title: "Spider Woman",
			description: "Jessica Drew might have solved the first mystery Ben Urich threw her way, but he’s got one or two more cases up his sleeve from other cities in the U.S. of A! It’s a road trip with Spider-Woman, Ben Urich and the Porcupine!",
			image: "spider-woman.jpg",
			year: "2004/4/5",
			recommended: "Si",
			edition: 2,
			creator: "Dennis Hopeless",
			qualification: 3,
		},
		{
			_id: 2,
			title: "Kanan",
			description: "When being a Jedi makes him a target, what can a Padawan do? Betrayed by those he once called friends, young Caleb Dume learns to survive as a smuggler!",
			image: "kanan.jpg",
			year: "2015/2/3",
			recommended: "No",
			edition: 1,
			creator: "Greg Weisman",
			qualification: 1,
		},
		{
			_id: 3,
			title: "The Amazing Spider-man",
			description: "Meet all of Spidey's deadly enemies, from the Green Goblin and Doctor Octopus to Venom and Carnage, plus see Peter Parker fall in love, face tragedy and triumph, and learn that with great power comes great responsibility",
			image: "amazing-spider-man.jpg",
			year: "2003/3/1",
			recommended: "No",
			edition: 1,
			creator: "Stan Lee",
			qualification: 5,
		},
		{
			_id: 4,
			title: "TWeirdworld",
			description: "Weirdworld is where the lost things go. Like the barbarian lord Arkon, who’s now prisoner of the underwater apes. • Or like his cellmate, a mysterious one-eyed man who appears to be made out of rock and calls himself a Crystal Warrior",
			image: "weirdworld.jpg",
			year: "2015/1/2",
			recommended: "Si",
			edition: 2,
			creator: "Stan Lee",
			qualification: 4,
		},
		{
			_id: 5,
			title: "The Punisher",
			description: "What does it take to be a Howling Commando? • Have the Howling Commandos gone a step too far? • And what will Frank do once they’ve crossed that line?",
			image: "the-punisher.jpg",
			year: "2004/3/3",
			recommended: "No",
			edition: 2,
			creator: "Gerry Conway",
			qualification: 2,
		},
		{
			_id: 6,
			title: "Civil War",
			description: "The Civil War never ended. Welcome to the Warzone, where six years of non-stop battle between the forces of the Blue and the Iron have split the nation down its center, utterly transforming it. In a world of new alliances and strange enemies, President Tony Stark and General Steve Rogers meet to make one last attempt at peace",
			image: "civil-war.jpg",
			year: "2015/1/2",
			recommended: "Si",
			edition: 1,
			creator: "Mark Millar",
			qualification: 5,
		},
	];

var users = 
	[
		{
			uName: 'admin',
			name: 'Juan Martin',
			password: 'admin',
			isAdmin: true,
		},
		{
			uName: 'juan',
			name : 'Juan Sebastian',
			password: 'juan',
			isAdmin: false,
		},
		{
			uName: 'daniela',
			name : 'Daniela Eliana',
			password: 'daniela',
			isAdmin: false,
		},
	];

